CREATE DATABASE HR;
USE HR;
SELECT * FROM HR;
ALTER TABLE HR RENAME COLUMN ï»¿id TO emp_id;
SELECT BIRTHDATE FROM HR;
SET sql_safe_updates=0;
UPDATE HR SET BIRTHDATE = CASE WHEN BIRTHDATE LIKE '%/%' THEN date_format(str_to_date(BIRTHDATE, '%m/%d/%Y'), '%Y-%m-%d')
						                    WHEN BIRTHDATE LIKE '%-%' THEN date_format(str_to_date(BIRTHDATE, '%m-%d-%Y'), '%Y-%m-%d')
									        ELSE NULL 
                                       END;   
ALTER TABLE HR MODIFY COLUMN BIRTHDATE DATE;
DESCRIBE HR;
SELECT HIRE_DATE FROM HR;

UPDATE HR SET HIRE_DATE = CASE WHEN HIRE_DATE LIKE '%/%' THEN date_format(str_to_date(HIRE_DATE, '%m/%d/%Y'), '%Y-%m-%d')
						                    WHEN HIRE_DATE LIKE '%-%' THEN date_format(str_to_date(HIRE_DATE, '%m-%d-%Y'), '%Y-%m-%d')
									        ELSE NULL 
                                       END; 
ALTER TABLE HR MODIFY COLUMN HIRE_DATE DATE;
DESCRIBE HR;
SELECT * FROM HR;
SELECT TERMDATE FROM HR;
UPDATE hr
SET termdate = CASE 
                WHEN termdate = '' THEN '0000-00-00'  
                ELSE date(str_to_date(termdate, '%Y-%m-%d %H:%i:%s UTC'))
              END
WHERE termdate IS NOT NULL AND termdate != ' ';
SELECT TERMDATE FROM HR;
DESCRIBE HR;
ALTER TABLE HR ADD COLUMN AGE INT;
UPDATE HR
SET AGE = timestampdiff(YEAR, BIRTHDATE, CURRENT_DATE());
SELECT BIRTHDATE, AGE FROM HR;

-- GENDER BREAK_DOWN IN COMPANY
SELECT GENDER, COUNT(*) AS GENDER_COUNT FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00' group by GENDER;   

-- RACE/ETHNICITY BREAKDOWN 
SELECT RACE, COUNT(*) AS RACE_COUNT FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00' GROUP BY RACE ORDER BY RACE_COUNT DESC;

-- AGE DISTRIBUTION OF COMPANY
SELECT 
CASE WHEN AGE>=18 AND AGE<=24 THEN '18-24'
     WHEN AGE>=25 AND AGE<=34 THEN '25-34'
     WHEN AGE>=35 AND AGE<=44 THEN '35-44'
     WHEN AGE>=45 AND AGE<=54 THEN '45-54'
     WHEN AGE>=55 AND AGE<=64 THEN '55-64'
     ELSE '65+'
     END AS AGE_GROUP, GENDER,
     COUNT(*) AS COUNT FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00' GROUP BY AGE_GROUP, GENDER ORDER BY AGE_GROUP; 

-- employees work at headquarters versus remote locations?

SELECT LOCATION, COUNT(*) AS COUNT FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00' group by LOCATION;

-- average length of employment for employees who have been terminated?
SELECT round(avg(datediff(termdate, HIRE_DATE))/365,2) as AVG_TERM_PERIOD FROM HR WHERE TERMDATE<=current_date() AND AGE>=18 AND TERMDATE != '0000-00-00';

-- gender distribution vary across departments and job titles
SELECT DEPARTMENT, GENDER, COUNT(*) AS COUNT FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00' GROUP BY DEPARTMENT, GENDER ORDER BY DEPARTMENT;      

-- TERMINATION RATE
SELECT 
    DEPARTMENT,
    TOTAL_COUNT,
    TERMINATED_COUNT,
    TERMINATED_COUNT / TOTAL_COUNT AS TERMINATED_RATE
FROM
    (SELECT 
        DEPARTMENT,
            COUNT(*) AS TOTAL_COUNT,
            SUM(CASE
                WHEN
                    TERMDATE <= CURRENT_DATE()
                        AND TERMDATE <> '0000-00-00'
                THEN
                    1
                ELSE 0
            END) AS TERMINATED_COUNT
    FROM
        HR
    WHERE
        AGE >= 18
    GROUP BY DEPARTMENT) AS SUBQUERY
ORDER BY terminated_rate DESC; 

-- distribution of employees across location_city and state
SELECT 
    LOCATION_STATE, COUNT(*) AS COUNT
FROM
    HR
WHERE
    AGE >= 18 AND TERMDATE = '0000-00-00'
GROUP BY LOCATION_STATE
ORDER BY COUNT DESC;

-- EMPLOYEES COUNT CHANGE OVER TIME BASED ON HIRE AND TERM DATES
SELECT YEAR, HIRES, TERMINATIONS, HIRES-TERMINATIONS AS NET_CHANGE, ROUND((HIRES-TERMINATIONS)/HIRES * 100, 2) AS NET_CHANGE_PERCENT FROM (SELECT YEAR(HIRE_DATE) AS YEAR, COUNT(*) AS HIRES, SUM(CASE WHEN TERMDATE<>'0000-00-00' AND TERMDATE<=CURRENT_DATE() THEN 1 ELSE 0 END) AS TERMINATIONS FROM HR WHERE AGE>=18 GROUP BY YEAR) AS SUBQUERY ORDER BY YEAR;

-- TENURE DISTRIBUTION OF EACH DEPARTMENT
SELECT DEPARTMENT, round(avg(datediff(termdate, HIRE_DATE))/365,0) AS AVG_TENURE FROM HR WHERE TERMDATE<=current_date() AND TERMDATE<>'0000-00-00' AND AGE>=18 GROUP BY DEPARTMENT;